repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        args: [--fix]
  - repo: local
    hooks:
      - id: verify-ops
        name: verify_ops
        entry: python scripts/verify_ops.py
        language: system
        pass_filenames: false
        stages: [pre-commit]
